### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by JamAbalos** [JamAbalos/dsn1675-project-1#8]
@thomasjbradley I'm suddenly having problems with my favicon, I'm not sure why.

**Comment by thomasjbradley** [comment]
What's happening? I can see it in Firefox/41.

**Comment by JamAbalos** [comment]
@thomasjbradley It's not showing up on chrome in any of my computers for some reason. If it works for you then I guess I'm okay?

**Comment by thomasjbradley** [comment]
There's an HTML validation error, try fixing that and seeing if it helps.

**Comment by JamAbalos** [comment]
@thomasjbradley I don't really understand the errors, I'm using validator.w3.org (if that's not the correct one let me know). So far it's highlighting:

> html="en-ca" - Element head is missing a required instance of child element title. ???what???
> 
> head - Stray start tag head.
> metaname="handheldfriendly" content="true" - cannot be represented as XML 1.0.
> metaname="viewport" content="width=device-width, initial-scale=1" - cannot be represented as XML 1.0.
> /head -Stray end tag head.
> 
> body - seen but an element of the same type was already open.
> /body - seen, but there were unclosed elements.

I've been looking at my code forever and I'm pretty sure there's no unclosed elements, I don't really understand how [head] is stray? I'm ignoring the XML1.0. errors because I think you said those are normal? And I don't have more than 1 [body] element. HELP!

**Comment by thomasjbradley** [comment]
The `<html>` element is missing `lang`, should be like this:

``` html
<html lang="en-ca">
```

And there are spaces missing between `meta` and `name` in the viewport tags.
